# Generated by Django 4.2.3 on 2023-07-29 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0002_profile_age_profile_place_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='name',
            field=models.CharField(max_length=140),
        ),
    ]
